# Generated by Django 4.0 on 2023-11-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_shift_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='color',
            field=models.CharField(blank=True, choices=[('Primary', 'bg-primary'), ('Info', 'bg-info'), ('Secondary', 'bg-secondary'), ('Light', 'bg-light'), ('Success', 'bg-success'), ('Danger', 'bg-danger'), ('Dark', 'bg-dark'), ('Warning', 'bg-warning')], default='Light', max_length=100, null=True),
        ),
    ]
