# Generated by Django 4.0 on 2023-11-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_groups'),
        ('attendance', '0007_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'shift', 'date')},
        ),
    ]
