# Generated by Django 4.0 on 2023-11-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendancerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='color',
            field=models.CharField(blank=True, choices=[('bg-primary', 'Blue'), ('bg-info', 'Light Blue'), ('bg-secondary', 'Gray'), ('bg-light', 'Light Gray'), ('bg-success', 'Green'), ('bg-success-l', 'Light Green'), ('bg-danger', 'Red'), ('bg-danger-l', 'Light Red'), ('bg-warning', 'Yellow'), ('bg-warning-l', 'Light Yellow'), ('bg-dark', 'Black')], default='bg-light', max_length=100, null=True),
        ),
    ]
