# Generated by Django 4.0 on 2023-11-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_shift_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
